spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-auth
          uri: lb://user-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

        - id: user-admin
          uri: lb://user-service
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=0

        - id: user-protected
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0

        - id: user-player
          uri: lb://user-service
          predicates:
            - Path=/player/**
          filters:
            - StripPrefix=0

        - id: tournament-service
          uri: lb://tournament-service
          predicates:
            - Path=/tournaments/**
          filters:
            - StripPrefix=1

        - id: tournament-player
          uri: lb://tournament-service
          predicates:
            - Path=/tournament/**
          filters:
            - StripPrefix=0

        - id: match-service
          uri: lb://match-service
          predicates:
            - Path=/match/**
          filters:
            - StripPrefix=0

server:
  port: 8080
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry:8761/eureka/}
  instance:
    prefer-ip-address: true
